name: Matteo Test github action 1

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'


      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build app for release
        run: msbuild src\YourProjectFile.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vswhere-path: 'C:\path\to\your\tools\'

      - name: Build with Maven Install
        run: mvn --batch-mode --update-snapshots install
      - name: Compile with Maven
        run: mvn --batch-mode --update-snapshots clean compile

